### ISSUE TITLE
[VnV Report] Reflection

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#458]
The information in this section will be used to evaluate the team members on the graduate attribute of Reflection. Please answer the following question:

1. In what ways was the Verification and Validation (VnV) Plan different from the activities that were actually conducted for VnV? If there were differences, what changes required the modification in the plan? Why did these changes occur? Would you be able to anticipate these changes in future projects? If there weren't any differences, how was your team able to clearly predict a feasible amount of effort and the right tasks needed to build the evidence that demonstrates the required quality? (It is expected that most teams will have had to deviate from their original VnV Plan.)

## Rubric Sections
- LO_Reflect

**Comment by joyxiao99** [comment]
Feel free to edit and add on....

In what ways was the Verification and Validation (VnV) Plan different from the activities that were actually conducted for VnV? 

If there were differences, what changes required the modification in
the plan? Why did these changes occur? 
- There were some changes that we made due to changes in the requirements. There were some areas where we decided was out of scope and communicated with our supervisor. In addition, during implementation we found that some changes were necessary to achieve a desirable user flow and experience. This resulted in some changes in the requirements and testing plan. Since we had not anticipated these requirement changes, modifications were required to the VnV plan to appropriately reflect the changes in requirements. In addition, we decided to create and include a usability survey to gather feedback from users.

Would you be able to anticipate these changes in future projects? 
- We would be able to anticipate most of these changes in future projects. Some changes that are difficult to anticipate are stakeholders changing the requirements which would require updating the requirements documentation and consequently the testing plans. With regards to the usability survey, we would likely consider including a usability survey earlier in the process, and therefore we would likely be able to anticipate this component of the VnV plan in the future.
